import { ClienteCompletoPage } from '../../../pages/cadastro_cliente/cliente_completo/ClienteCompletoPage.js';
import { PessoaPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Pessoa/PessoaPage.js';
import { RefBancariaPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Referencia/ref_bancaria/RefBancariaPage.js';
import { RotaPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Rota/RotaPage.js';
import { TelefonePage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Telefone/TelefonePage.js';
import { EnderecoPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_endereco/EnderecoPage.js';

describe('Register complete client', () => {

    beforeEach(() => {
        cy.visit('/');
        cy.clearAllSessionStorage();
        cy.login();
        cy.urlAposLogin();
        cy.tituloPagina();
    })

    context('Complete customer registration - including bank reference.', () => {

        it('1.Full customer CPF - PIX key type Correct phone number', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto(); 
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixPhone()
            RefBancariaPage.keyPixPhone()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        })  

        it('2.Full customer CPF - PIX key type Correct email', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto(); 
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixEmail()
            RefBancariaPage.keyPixEmail()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        }) 

        it('3.Full customer CPF - PIX key type CPF CNPJ correct', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto(); 
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixCpfCnpj()
            RefBancariaPage.keyPixCPF()
            GeneralRefBanking.clicarSalvarRefBanclickSalvarReferenciaBancariacaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        }) 

        it('4.Full customer CPF - PIX key type CPF CNPJ correct', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto(); 
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixRandom()
            RefBancariaPage.keyPixRandom()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        }) 

        it('5.Full customer CPF - validate PIX key type Incorrect phone number', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto();
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixPhone()
            RefBancariaPage.keyPixPhoneWrong()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixPhoneInvalid()
        })  

        it('6.Full customer CPF - validate PIX key type. Incorrect email', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto();
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixEmail()
            RefBancariaPage.keyPixEmailWrong()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixEmailInvalid()
        })  

        it('7.Full customer CPF - validate CPF key type. Incorrect CNPJ', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto();
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixCpfCnpj()
            RefBancariaPage.typeKeyPixRandom()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixCpfCnpjInvalid()
        })  

        it('8.Full customer CPF - validate incorrect random key type', () => {

            ClienteCompletoPage.clickMenuOpcoes();
            ClienteCompletoPage.clickOpcaoClienteCompleto();
            PessoaPage.fillCPFCliente();
            PessoaPage.fillNomeCompleto();
            PessoaPage.fillNomeSocial();
            PessoaPage.fillDataNascimento();
            PessoaPage.chooseSexoCliente();
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio(); 
            EnderecoPage.clickAbaEndereco(); 
            EnderecoPage.clickAdicionarNovoEndereco();
            EnderecoPage.tipoEndereco()
            EnderecoPage.validateEnderecoVazio();
            EnderecoPage.clickAbrirTipoEndereco();
            EnderecoPage.chooseTipoEndereco()
            EnderecoPage.fillCEPEndereco()
            EnderecoPage.fillNumeroEndereco()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSalvarEndereco()
            EnderecoPage.infoEnderecoAdicionado()
            RotaPage.clickAbaRota() 
            RotaPage.clickAdicionarNovaRota()
            RotaPage.validateRotaVazia()
            RotaPage.chooseTipoEnderecoRota()
            RotaPage.addRotaCompleta()
            RotaPage.validadeRotaAdicionada()
            TelefonePage.clickAbaTelefone() 
            TelefonePage.clickAdicionarNovoTelefone()
            TelefonePage.validateTelefoneVazio()
            TelefonePage.chooseTipoTelefone()
            TelefonePage.fillNumeroTelefone()
            TelefonePage.fillRamalTelefone()
            TelefonePage.clickSalvarTelefone()
            TelefonePage.validateTelefoneAdicionado()
            TelefonePage.validateMessageTelefoneAdicionado()
            ClienteCompletoPage.ClickAbaReferencias() 
            GeneralRefBanking.clickAbaReferenciaBancaria()
            GeneralRefBanking.validateAbaReferenciaBancariaVazia()
            GeneralRefBanking.clickAddNovaReferenciaBancaria()
            GeneralRefBanking.modalReferenciaBancariaVazia()
            RefBancariaPage.fillBanco()
            RefBancariaPage.fillAgencia()
            RefBancariaPage.fillConta()
            RefBancariaPage.fillDataAbertura()
            RefBancariaPage.fillTelefone()
            RefBancariaPage.fillGerente()
            RefBancariaPage.fillEmail()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixRandom()
            GeneralRefBanking.clickSalvarReferenciaBancaria()
            GeneralRefBanking.messageReferenciaBancariaAdicionadaSucesso()
            GeneralRefBanking.infoReferenciaBancariaAdicionada()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixRandomInvalid()
        })  
    })
})