import { ClienteCompletoPage } from '../../../pages/cadastro_cliente/cliente_completo/ClienteCompletoPage.js';
import { PessoaPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Pessoa/PessoaPage.js';
import { GeneralRefBanking } from '../../../pages/cadastro_cliente/cliente_completo/aba_Referencia/ref_bancaria/RefBancariaPage.js';
import { RotaPage, RotaPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Rota/RotaPage.js';
import { TelefonePage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Telefone/TelefonePage.js';
import { EnderecoPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_endereco/EnderecoPage.js';

describe('Cadastrar cliente completo', () => {

    beforeEach(() => {
        cy.visit('/')
        cy.clearAllSessionStorage()
        cy.login()
        cy.urlAposLogin()
        cy.tituloPagina()
    })

    context('Cadastro de cliente completo - incluindo referencia bancária', () => {

        it('1.Cliente completo CPF - tipo chave PIX Telefone correto', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto() 
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixPhone()
            RefBancariaPage.keyPixPhone()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        })  

        it('2.Cliente completo CPF - tipo chave PIX Email correto', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto() 
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixEmail()
            RefBancariaPage.keyPixEmail()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        }) 

        it('3.Cliente completo CPF - tipo chave PIX CPF CNPJ correto', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto() 
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixCpfCnpj()
            RefBancariaPage.keyPixCPF()
            GeneralRefBanking.clicarSalvarRefBanclickSaveRefBankingcaria()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        }) 

        it('4.Cliente completo CPF - tipo chave PIX CPF CNPJ correto', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto() 
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixRandom()
            RefBancariaPage.keyPixRandom()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateModalAguardeCarregando()
            ClienteCompletoPage.validateMessageSalvoSucesso()
        }) 

        it('5.Cliente completo CPF - validar tipo de chave PIX Telefone incorreto ', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto()
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixPhone()
            RefBancariaPage.keyPixPhoneWrong()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixPhoneInvalid()
        })  

        it('6.Cliente completo CPF - validar tipo de chave PIX Email incorreto ', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto()
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixEmail()
            RefBancariaPage.keyPixEmailWrong()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixEmailInvalid()
        })  

        it('7.Cliente completo CPF - validar tipo de chave CPF CNPJ incorreto ', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto()
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixCpfCnpj()
            RefBancariaPage.typeKeyPixRandom()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixCpfCnpjInvalid()
        })  

        it('8.Cliente completo CPF - validar tipo de chave Aleatória incorreto ', () => {

            ClienteCompletoPage.clickMenuOpcoes()
            ClienteCompletoPage.clickOpcaoClienteCompleto()
            PessoaPage.fillCPFCliente()
            PessoaPage.fillNomeCompleto()
            PessoaPage.fillNomeSocial()
            PessoaPage.fillDataNascimento()
            PessoaPage.chooseSexoCliente()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            ClienteCompletoPage.validateMessageEnderecoObrigatorio() //mensagem de endereço obrigatório após tentar salvar sem adicionar um endereço
            EnderecoPage.clickAbaAdress() //CADASTRAR ENDEREÇO
            EnderecoPage.clickAddNewAdress()
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade()
            EnderecoPage.clickOpenTypeAdress()
            EnderecoPage.typeAdress()
            EnderecoPage.cepAdress()
            EnderecoPage.numberAdress()
            ClienteCompletoPage.validarBotaoSalvarDesabilitado()
            EnderecoPage.clickSaveAdress()
            EnderecoPage.infoAdressAdded()
            RotaPage.clickAbaRoute() //CADASTRAR ROTA
            RotaPage.clickAddedNewRoute()
            RotaPage.modalRouteEmptyValidade()
            RotaPage.typeAdressRoute()
            RotaPage.routaComplete()
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone() //CADASTRAR TELEFONE
            TelefonePage.clickAddedNewPhone()
            TelefonePage.modalPhoneEmptyValidade()
            TelefonePage.typePhone()
            TelefonePage.numberPhone()
            TelefonePage.ramalPhone()
            TelefonePage.clickSavePhone()
            TelefonePage.infoPhoneAdded()
            TelefonePage.messPhoneAddedSucess()
            ClienteCompletoPage.ClickAbaReferencias() //REFERENCIA
            GeneralRefBanking.clickAbaRefBanking() //CADASTRAR REFERENCIA BANCÁRIA
            GeneralRefBanking.validateAbaRefBankingEmpty()
            GeneralRefBanking.clickAddNewRefBanking()
            GeneralRefBanking.modalRefBankingEmpty()
            RefBancariaPage.bank()
            RefBancariaPage.agency()
            RefBancariaPage.account()
            RefBancariaPage.dateOpening()
            RefBancariaPage.phone()
            RefBancariaPage.manager()
            RefBancariaPage.email()
            RefBancariaPage.cpfAccountHolder()
            RefBancariaPage.nameAccountHolder()
            RefBancariaPage.typeAccount()
            RefBancariaPage.operation()
            RefBancariaPage.formPayment()
            RefBancariaPage.typeKeyPixRandom()
            GeneralRefBanking.clickSaveRefBanking()
            GeneralRefBanking.messRefBankingAddedSucess()
            GeneralRefBanking.infoRefBankingAdded()
            ClienteCompletoPage.clickSalvarClienteCompleto()
            GeneralRefBanking.messRefBankingKeyPixRandomInvalid()
        })  
    })
})